### ISSUE TITLE
Output on non existing folders

### ISSUE THREAD

**Issue by Jonatthu** [damieng/DamienGKit#13]
I found this piece of code on the internet to be called before create the file or in case the folder destination does not exist.

`System.IO.FileInfo file = new System.IO.FileInfo(filePath);
`

I want to modify a little bit the manager and check if the nested folder does exist or create it and then proccess the file.

`manager.StartNewFile(@"../../"+Settings.ProjectName+".Services/BaseServices/" + model.Name + "BaseService.cs");`

How to do this?

**Comment by Jonatthu** [comment]
`DirectoryInfo di = Directory.CreateDirectory(@"C:\Users\J\TestFolders\" + model.Name);
`
This line of code works on t4!

**Comment by damieng** [comment]
Maybe send a PR so we can fix it for everyone?
