### ISSUE TITLE
Files are generated under the codetemplates folder

### ISSUE THREAD

**Issue by mmu69** [damieng/DamienGKit#14]
I've included the MultipleOutputHelper in ..\CodeTemplates\MvcView so. This is working wonderfull for my modified List.cs.t4, but the extra file created with the manager is created in the ..\CodeTemplates\MvcView folder.
Is this expected or am i doing something wrong?
VS2017 15.5.3

**Comment by damieng** [comment]
Can you explain your folder structure a bit more along with where the output was expected? Thanks

**Comment by mmu69** [comment]
This is how the CodeTemplates folder inside my project looks like. Lis.cs.t4 is using the MultipleOutputHelper to create an aditional file called "_IndexList.cshtml"
![image](https://user-images.githubusercontent.com/3749013/35197031-7a90f71c-feda-11e7-86f7-e828c42dcfc6.png)

When i scaffold the list template (by adding a view in a views folder, by right clicking on the "return view" statement inside a controller or scaffolding a mvc controller including views), i expeected the _lindexList.cshtml to be in the same folder as the Index.cshtml. Like this:
![image](https://user-images.githubusercontent.com/3749013/35197101-4a5cdee8-fedb-11e7-972e-25763dfa75ec.png)

The additional file "_IndexList.cshtml" is not in the views folder together with "Index.cshtml", but is created in the CodeTemplates folder with the t4 files
![image](https://user-images.githubusercontent.com/3749013/35197154-d52a015e-fedb-11e7-97de-c9e42624fb05.png)

**Comment by damieng** [comment]
The helper does not know or understand anything about MVC as it is a generic helper designed for all sorts of code generation (it was actually originally written for generating multiple files for LINQ to SQL).

The default behavior is to generate the files as sub-items beneath the T4 file that generates them and to put the files in the same folder as the T4 file.

I think from your screenshots then it is behaving as designed.  

For this to put files in a flexible way we'd need to add support for an extra folder name to the Process call inside List.cs.t4 I suspect, e.g.

`manager.Process(true, '..\..\t406')`

**Comment by damieng** [comment]
I looked into this a little more - the code that adds the files to the solution would also have to be changed - right now it adds them as sub-files under the generated file.  If you want them somewhere else then it has no idea which files it 'owns' so can't delete old files any more...

**Comment by damieng** [comment]
Can't reliably build this in as per the notes above. If people need this behavior they'll have to hack the helper directly and somehow just "know" which files to delete when it recreates.
