### ISSUE TITLE
CRC32 Performance

### ISSUE THREAD

**Issue by jayakrishnabh** [damieng/DamienGKit#17]
Hi, I am using the GitHub's latest CRC32. 
During performance test, for 55KB buffer size, it takes 1.36 ms for processing.
Can this be improvised further by parallel processing or any other mechanism. 
Please share the latest if performance can be improved.

Attaching the performance captured for CalculateHashmethod.
![crc32performance](https://user-images.githubusercontent.com/17740686/41032114-1c4726dc-69a0-11e8-84db-c189205d3e9a.PNG)

**Comment by damieng** [comment]
You can't parallel process it but there are some tricks with slicing the table up if you don't mind the lookup table going from ~1KB to 8KB that Intel developed.   I've put a new class up called [Crc32Slice8](https://github.com/damieng/DamienGKit/blob/master/CSharp/DamienG.Library/Security/Cryptography/Crc32Slice8.cs) you could try - it should be drop-in compatible.  Let me know how you get on - I've not run extensive benchmarks on it yet.

**Comment by damieng** [comment]
A 16 slice version is possible but if the performance increase in your environment is as bad as that it probably isn't worth the effort.

**Comment by jayakrishnabh** [comment]
Hi Damien, It would be great to have 16 slice version if it improves the performance further better. 
Please share the 16 slice version.  Will try this so that our performance increases further.

**Comment by damieng** [comment]
Crc32Slice16 is now checked in.

**Comment by damieng** [comment]
I don't have any other ideas for improved performance so I'm going to close this down now.
