### ISSUE TITLE
fonts`

### ISSUE THREAD

**Issue by zartan9** [damieng/DamienGKit#21]
hi im totally new trying to make a ch8 font /altar one of yours for a game..is there a link how to go about this? thank you..

**Comment by damieng** [comment]
I use the BASINC editor available from https://arda.kisafilm.org/blog/?cat=13&lang=en - just go into `Tools > UDG Character Editor` 

To test a font drag your .ch8 file onto any of my ZX Origins pages and it will re-render all the screenshots with your file.
