### ISSUE TITLE
Package the T4 for distribution

### ISSUE THREAD

**Issue by mwpowellhtx** [damieng/DamienGKit#4]
At the moment I've cloned the repo as a submodule, but this just doesn't feel right. I certainly don't need the CSharp bits, for instance.

I don't know if NuGet is an appropriate distribution channel for T4-based concerns? Considering also that T4 is a VS extension.

It's a thought.

Thanks!

**Comment by damieng** [comment]
I'm not sure you can actually package it as a NuGet package.  I'd recommend just copying the file into your repo.  It hasn't changed in years.

**Comment by mwpowellhtx** [comment]
Please find my [PR](http://github.com/damieng/DamienGKit/pull/5) at your convenience. Thank you...

**Comment by damieng** [comment]
Hi, decided not to go ahead with NuGet packaging. I really don't want this to be a shared library. It's just web blog sample code with unit tests. People should adapt/copy as appropriate.

**Comment by mwpowellhtx** [comment]
No problem. Thanks for letting me know anyway. Moving forward, you expect the library to stay pretty much as-is? In other words, I'll be happy to package it myself, as I think it provides good value for folks on this path. At least it did for me. Thanks again.

**Comment by damieng** [comment]
It's possible additional classes will come depending on my own personal needs. If you do package it up please don't publish it publicly - I don't want the confusion.

**Comment by mwpowellhtx** [comment]
I'm running it by you as a first right of refusal. If you're unwilling to publish it, I will; just giving you the nod ahead of time. Along which lines, you expect additional parts to come, I am more than happy to coordinate some packaging along these lines. Thanks again.

**Comment by damieng** [comment]
No quite sure what you mean by that.
