### ISSUE TITLE
Manager.Process does not seem to process the previous file

### ISSUE THREAD

**Issue by mwpowellhtx** [damieng/DamienGKit#7]
Hello,

It's been awhile since I picked up the ``ttinclude`` files. They've been working pretty good for the most part. But I have an issue now. 

I have a case where I have two different sections of an Xml document that I am loading and want to output to two different files. Of itself, I have one section working just fine. However, when I add the second section, the first of the two sections does not process. I confirmed I still get the second (last?) section just fine, as per the output time stamp (just now), ``2016-04-21T20:43:18.3692075-04:00``.

In my generation method, I start with the following:

```C#
manager.StartNewFile(GetGeneratedCSharpPath(Host, name));
```

Following which, after each iteration, I call this:

```C#
manager.Process(true);
```

Where ``name`` is the name of the output class, i.e. *Instructions* in ``Instructions.Generated.cs``.

Perhaps it is a bug in the ttinclude, I do not know. I could be user related, just don't know how to debug it, per se. Only that the first (not the last) output is definitely not being handled properly.

Any ideas?

**Comment by mwpowellhtx** [comment]
Ah, okay. User error. I was editing a version of the Xml file in a boilerplate project, apart from the T4-based module. Works like a champ!

**Comment by damieng** [comment]
The other thing I was going to mention is that ```manager.Process``` only needs to be called once at the very end of the template regardless of how many files you want.

**Comment by mwpowellhtx** [comment]
Yessir. I did that, too, during troubleshooting. Thanks...
