### ISSUE TITLE
CRC32 with offset

### ISSUE THREAD

**Issue by eikesauer** [damieng/DamienGKit#8]
Hi Damien, 

thanks for your code!

I met a problem in the CRC32 code, though. It looks like somebody already reported it on your blog, but as the code still is as it is...

When calling HashAlgorithm.TransformBlock() with say a byte array of size 100, an inputOffset of 10 and an inputCount of 3...

        static UInt32 CalculateHash(UInt32[] table, UInt32 seed, IList<byte> buffer, int start, int size)
        {
            var crc = seed;
            for (var i = start; i < size - start; i++)

...the code tries to loop from 10 upwards to <7 and will not hash any bytes.
It really should be "for (var i = start; i < size + start; i++)" to loop from 10 to <13.

Ciao,
  Eike

**Comment by eikesauer** [comment]
Now that was a quick change - after all those years! :o) 
Thanks!

**Comment by damieng** [comment]
Yeah, I could have sworn I fixed this once before... but I guess it didn't make it as far as GitHub. :blush:

**Comment by eikesauer** [comment]
According to you blog comments, you once had "size" and "fixed" it to "size - start".
Well, Rome wasn't built in a day either. ;)
