### ISSUE TITLE
Setting HashValue in Crc32.cs

### ISSUE THREAD

**Issue by minustar** [damieng/DamienGKit#9]
It seams that that field is `protected internal`, and therefore cannot be set. Perhaps I am doing something wrong. Using .Net 4.6.

**Comment by damieng** [comment]
HashValue is internal state - this is common for hash providers where the final step performs additional computation. In the case of Crc32 it XOR's the final state.

If you want to just hash a whole byte array you can simple do;

```csharp
uint hash = Crc32.Compute(myArray);
```

If you wish to stream result it's just the standard .NET HashAlgorithm interface. Here's an example of that also showing how to output the int32 as a hex string;

```csharp
var crc32 = new Crc32();
var hash = "";

using (var fs = File.Open("c:\\myfile.txt", FileMode.Open))
  foreach (var b in crc32.ComputeHash(fs)) hash += b.ToString("x2").ToLower();

Console.WriteLine("CRC-32 is {0}", hash);
```
